#!/bin/sh

export FLOPREFIX
export flofmach && export flofdistro && export flofarch && export osfullname && export osname && export osversion && export osbuild && export osbuildcodename && export updatepatch && export year && export layer && export nxtlayer && export distrobase && export user && export specialbuildattempt

#bash "$FLOPREFIX"usr/lib/floflis/layers/soil/to-merge_firstboot.sh
