#!/bin/sh

nm="Floflis Fixer"
vs="r1"
fixerversion="""
        \e[1;42m $nm \e[0m\e[100m version $vs \e[0m
        Assist to fix issues on your device.
        \e[100m Created in 12-20-2020 by Daniell Mesquita \e[0m
"""

if [ "$1" = "" ]; then
   echo "$fixerversion"
   echo "Type 'fixer --help' (without quotes) to see a list of available commands."
fi

# displays help message with a list of commands:
if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
   echo "        \e[1;42m $nm $vs \e[0m"
   echo "Use these commands after/together with 'fixer' command."
   echo "  modem-disable                       If your phone tethering keeps disconnecting the Internet on your device"
   echo "  modem-enable                        If you need to use it and it will have no conflict with phone tethering"
   echo "Available commands:"
   echo "----------------------------------------------------------"
   echo "Information:"
   echo "  --help, -h                          Shows all available commands"
   echo "  --version, -v                       Shows the version of $nm"
fi

if [ "$1" = "modem-enable" ]; then
sudo systemctl enable ModemManager.service
sudo systemctl start ModemManager.service
sudo NetworkManager
echo "(✓) This fix is done! But please restart your device to complete this fix."
fi

if [ "$1" = "modem-disable" ]; then
sudo systemctl disable ModemManager.service
sudo systemctl stop ModemManager.service
sudo NetworkManager
echo "(✓) This fix is done! But please restart your device to complete this fix."
fi

if [ "$1" = "--version" ] || [ "$1" = "-v" ]; then
   echo "$vs"
fi
